---
  # Some files to load in, and store data
  Pedestal_file: '\\HEROS\dbloech\Alibava_measurements\VC811929\Pedestal.hdf5'
  Delay_scan: '\\HEROS\dbloech\Alibava_measurements\Alibava configs\delay_scan.txt'
  Charge_scan: '\\HEROS\dbloech\Alibava_measurements\Alibava configs\charge_scan.txt'
  Measurement_file:
    - '350V.hdf5'
    #- '330V.hdf5'
    #- '310V.hdf5'
    #- '290V.hdf5'
    #- '270V.hdf5'
  Output_folder: ''
  Output_prefix: ''

  # Event analysis parameters
  Charge_scale: True # Convert ADC to electrons
  Plot_single_event: 29895
  SN_cut: 7 # Minimum height of hit
  SN_ratio: 0.4 # Ratio at which the program searches for nearby hits below the SN cut
  SN_cluster: 5 # SN what the whole cluster must have at minimum to be considered, values great then 7 are useless
  timing:
    - 0 # Minimum timing window
    - 75 # Maximum timing window
  max_cluster_size: 7 # Directly affects runtime!!!
  sensor_type: "n-in-p" # Sensor Material
  automasking: True # Tries to find non physical or garbage hits (wrong ADC direction) and excludes them from calculation (costs moderate CPU)
  optimize: True # Use Numba jit optimizer or not --> Warning no progress bar can be shown with this true
  additional_analysis:
      - langau
      - CCE
      - chargesharing

  # If you name a parameter like the additional analysis entry, you can easily access this data in the analysis
  chargesharing: "sdf"



