---
  # Some files to load in, and store data
  Pedestal_file: 'D:\Data\VC811929\Pedestal.hdf5'
  Delay_scan: 'D:\Data\VC811929\delay_scan.txt'
  Charge_scan: 'D:\Data\VC811929\charge_scan.txt'
  Measurement_file:
    - 'D:\Data\VC811929\330V.hdf5'
  Output_folder: ''
  Output_name: '100V'

  # Event analysis parameters
  Charge_scale: True # Convert ADC to electrons
  Processes: 6
  Plot_single_event: 1000
  SN_cut: 6 # Minimum height of hit
  SN_ratio: 0.5 # Ratio at which the program searches for nearby hits below the SN cut
  SN_cluster: 5 # SN what the whole cluster must have at minimum to be considered, values great then 7 are useless
  timing:
    - 0 # Minimum timing window
    - 75 # Maximum timing window
  max_cluster_size: 7 # Directly affects runtime!!!
  sensor_type: "n-in-p" # Sensor Material
  automasking: True # Tries to find non physical or garbage hits (wrong ADC direction) and excludes them from calculation (costs moderate CPU)
  optimize: True # Use Numba jit optimizer or not --> Warning no progress bar can be shown with this true, or may be misleading
  additional_analysis:
      - langau
      #- CCE
      #- chargesharing

  langau:
    clustersize: [1,2,3] # Defines which cluster sizes should be fitted with a langau, list of values defines only these, negative values are for all clustersizes



